"""Added library from branch in transaction

Revision ID: 073bd9979a52
Revises: a82aba9d55f3
Create Date: 2024-04-30 00:42:36.068355

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '073bd9979a52'
down_revision = 'a82aba9d55f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('library_id', sa.Integer(), nullable=True))
    op.drop_constraint('transactions_branch_id_fkey', 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'libraries', ['library_id'], ['id'])
    op.drop_column('transactions', 'branch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key('transactions_branch_id_fkey', 'transactions', 'libraries', ['branch_id'], ['id'])
    op.drop_column('transactions', 'library_id')
    # ### end Alembic commands ###
