"""Added due date time

Revision ID: 08a44ca824ae
Revises: 184fca7a29cf
Create Date: 2024-04-30 00:51:26.956024

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '08a44ca824ae'
down_revision = '184fca7a29cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'due_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'due_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
