"""Added checkout time

Revision ID: 184fca7a29cf
Revises: 263ba7fbd88a
Create Date: 2024-04-30 00:50:03.573167

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '184fca7a29cf'
down_revision = '263ba7fbd88a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
