"""Added checkout time

Revision ID: 263ba7fbd88a
Revises: b93da259ef3b
Create Date: 2024-04-30 00:49:03.593184

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '263ba7fbd88a'
down_revision = 'b93da259ef3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'checkout_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'checkout_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
