"""Changed Time

Revision ID: 3b6b0a4471ce
Revises: 08a44ca824ae
Create Date: 2024-04-30 00:53:50.925866

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '3b6b0a4471ce'
down_revision = '08a44ca824ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'return_date')
    op.drop_column('transactions', 'checkout_date')
    op.drop_column('transactions', 'due_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('checkout_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('return_date', sa.DATE(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
