"""Added Transaction relationship to User

Revision ID: a82aba9d55f3
Revises: 5da7742db46c
Create Date: 2024-04-29 22:10:21.263496

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'a82aba9d55f3'
down_revision = '5da7742db46c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
