"""Added checkout time

Revision ID: b93da259ef3b
Revises: fb28189ebe89
Create Date: 2024-04-30 00:48:29.602194

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'b93da259ef3b'
down_revision = 'fb28189ebe89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
